### ISSUE TITLE
Jump command not working in Linux client

### ISSUE THREAD

**Issue by Koltak** [codeauroraforum/mfgtools#25]
Hello,

I am currently trying to get the mfgtoolcli to work, but there are some issues, that I can't resolve on my own:

When trying to flash my board using the mfgtool, using the jump command doesn't seem to have any effect.
The command chain in question is:
```XML
<CMD state="BootStrap" type="boot" body="BootStrap"
	file="firmware/u-boot.imx">Loading U-boot</CMD>
<CMD state="BootStrap" type="load" file="firmware/zImage"
	address="0x12000000" loadSection="OTH" setSection="OTH"
	HasFlashHeader="FALSE">Loading Kernel.</CMD>
<CMD state="BootStrap" type="load"
	file="firmware/zImage.dtb" address="0x18000000"
	loadSection="OTH" setSection="OTH" HasFlashHeader="FALSE">Loading device
	tree.</CMD>
<CMD state="BootStrap" type="load"
	file="firmware/image.cpio.gz.u-boot"
	address="0x12C00000" loadSection="OTH" setSection="OTH"
	HasFlashHeader="FALSE">Loading Initramfs.</CMD>
<CMD state="BootStrap" type="jump" >Jumping to OS image.</CMD>
```

For my setup, I tried both: Native Linux with Windows guest, as well as native Windows with Linux guest.
For both setups, the WIndows version seems to work, while the Linux doesnt.

Analyzing the USB traffic with wireshark leads me to believe, that we simply do not get answers from the board, i.e. the Windows version shows an interrupt coming from the board after sending the jump command, while the Linux version shows nothing.

The curious thing about this behaviour is, that the packages sent look exactly the same for each setup (Win-host packets == Lin-guest packets and Lin-host packets == Win-guest packets).
This leads me to believe, that some earlier stage of the setup differs between the Windows and Linux edition.

**Comment by nxpfrankli** [comment]
GetHabType need be call in jump command.  I am not sure why need at linux version yet.
