### ISSUE TITLE
Poor file transfer performance on windows mfgtools v2.8? 

### ISSUE THREAD

**Issue by thkaw** [codeauroraforum/mfgtools#37]
Hi,

I found when I using mfgtools 2.6.2, the transfer data(system.img, userdata.img etc.) speed can reach 18MB/s

But I compile latest windows mfgtools(v2.8). The speed drop to only around 2.8MB/s

Is any change make this result?

Thanks

**Comment by nxpfrankli** [comment]
Not sure,  Can you try our latest uuu tools?  
Which platform do you use?

**Comment by thkaw** [comment]
My compile platform is Windows.

But I also try 2.3.2 source code to compile with Visual Studio 2017 Enterprise+Windows 10 latest version.
The speed still low.

I don't find 2.6.2 source code that I can't verify the problem is.

Is there need adjust any special compiler parameter to compile?

I will try to compile uuu now.

**Comment by thkaw** [comment]
@nxpfrankli We got the problem. We release and testing in wrong build profile.

Should using RELEASE build, but accident using DEBUG build when compile project.
